baseURL = "https://www.mathewinkson.com/"
languageCode = "en-AU"
title = "Mathew Inkson"
disableKinds = ["section"]
enableRobotsTXT = true
titleCaseStyle = "AP"
timeZone = "Australia/Hobart"

[frontmatter]
  lastmod = ["lastmod"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      guessSyntax = true
      noClasses = false

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "assets3p"
    target = "assets"

[params]
  categories = ["Music","Technology","Sport","Television","Government","Miscellaneous"]
  canonURL = "https://www.mathewinkson.com"
  author = "Mathew Inkson"
  ogimage = "/img/og.png"
  sitename = "Mathew Inkson"
  facebook = "https://facebook.com/imathew"
  github = "https://github.com/imathew"
  adminEmailHash = "964727ff57b3aa9abf64909b95a1902f"
  imagesize_inline = 1400
  imagesize_thumb = 620
  imagesize_gallery = 2600
  
  # Date Format Strings (Go time format)
  date_format_iso = "2006-01-02"
  date_format_long = "January 2, 2006"
  date_format_rfc3339 = "2006-01-02T15:04:05Z0700"

[permalinks]
  posts = '/:year/:month/:slug/'
  pages = ":slug"

[taxonomies]
  category = "categories"

[imaging]
  quality = 80
  resampleFilter = "Lanczos"
  anchor = "Center"